Update set-mariadb-node
all working now, grant to mysql.

diff --git a/hooks/set-mariadb-node b/hooks/set-mariadb-node
--- a/hooks/set-mariadb-node
+++ b/hooks/set-mariadb-node
@@ -42,6 +42,24 @@ echo "MYSQLD not running" + $running
     ${OPENSHIFT_MARIADB_DIR}/michael44/mariadb-5.5.34-linux-x86_64/bin/mysqld --defaults-file=${OPENSHIFT_MARIADB_DIR}/config.cnf > t3.txt 2>&1 &
     sleep 10
     ${OPENSHIFT_MARIADB_DIR}/michael44/mariadb-5.5.34-linux-x86_64/bin/mysql -uroot -e "INSTALL PLUGIN scaledb SONAME 'ha_scaledb.so'"
+
+
+
+
+
+source $OPENSHIFT_CARTRIDGE_SDK_BASH
+
+dbname=$OPENSHIFT_APP_NAME
+socket_file=$OPENSHIFT_MARIADB_DB_SOCKET
+username=$OPENSHIFT_MARIADB_DB_USERNAME
+password=$OPENSHIFT_MARIADB_DB_PASSWORD
+
+# TODO: Should be we running mysql_secure_installation
+echo "GRANT ALL ON *.* to root@'%'; flush privileges;" | ${OPENSHIFT_MARIADB_DIR}/michael44/mariadb-5.5.34-linux-x86_64/bin/mysql -uroot > /dev/null || error "Failed to setup initial root user" 187
+
+
+
+
 fi
 
 
